version: 2.1

commands:
  checkout-shallow:
    description: "Do a shallow checkout of the repository"
    steps:
      - run:
          name: Install git and openssh
          command: apt-get update && apt-get -qq -y install openssh-client git
      - run:
          name: Store the keyid for the git repo
          command: mkdir -p $HOME/.ssh && ssh-keyscan $(echo ${CIRCLE_REPOSITORY_URL} | sed 's,.*@\([^:]*\):.*,\1,') > $HOME/.ssh/known_hosts
      - run:
          name: Clone the repo
          command: |
            set -x
            env
            if [ -n "$CIRCLE_PR_NUMBER" ]
            then
              echo === Checking out PR "$CIRCLE_PR_NUMBER" from "$CIRCLE_REPOSITORY_URL"
              git clone --depth 1 $CIRCLE_REPOSITORY_URL /opt/project
              cd /opt/project
              git fetch --depth 1 origin +refs/pull/${CIRCLE_PR_NUMBER}/merge
              git checkout -qf FETCH_HEAD
            else
              echo === Checking out branch "${CIRCLE_BRANCH}" from "$CIRCLE_REPOSITORY_URL"
              git clone --depth 1 --branch $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL /opt/project
            fi
            git show -s
      - persist_to_workspace:
          root: /opt
          paths:
            - project

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout-shallow
  verify:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: find
          command: find /opt -ls

workflows:
  version: 2

  build-and-test-all:
    jobs:
      - build
      - verify:
          requires:
            - build
